module.exports = {
    "version": "0.2",
    "language": "en",
    "words": [
        "APPDATA",
        "bmatcuk",
        "coverprofile",
        "dropboxignore",
        "doublestar",
        "fyne",
        "fsnotify",
        "globbing",
        "golangci",
        "golint",
        "gofmt",
        "goweight",
        "Hinterhofer",
        "jondot",
        "kichik",
        "LOCALAPPDATA",
        "nolint",
        "ouzi-dev",
        "rjeczalik",
        "sp1thas",
        "spiretechnology",
        "stretchr",
        "systray",
        "unignore", // not a correct word...
        "unignoreable", // not a correct word...
        "USERPROFILE",
        "xattr",
        "xorg",
        "xquartz",
    ],
    "ignorePaths": [
        ".git",
        "*.exe",
        "*.log",
        "*_generated.go",
        "assets",
        "fyne-cross",
        "go.mod",
        "go.sum",
        "node_modules",
    ],
}
