name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Install dependencies
        run: go mod download
      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
      - name: Generate
        run: go generate ./...
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | bash -s docker
      - name: Package for Windows
        run: fyne-cross windows -pull -arch=*
      - name: Package for Linux
        run: fyne-cross linux -pull -arch=*
      - name: Package for MacOS
        run: fyne-cross darwin -pull -arch=*
      - name: PreparePackages
        run: |
          mkdir pkg-dist
          for file in fyne-cross/dist/*/* ; do cp "$file" "pkg-dist/$(echo $file | sed -n -E "s/fyne-cross\/dist\/([^\/]+)\/([^\/.]+)([^\/]+)$/\2_${{env.RELEASE_VERSION}}_\1\3/p")" ; done |
          echo "done"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          append_body: true
          generate_release_notes: true
          files: |
            pkg-dist/*
            LICENSE
