name: Release

on:
  push:
    tags:
      - v*

jobs:
  build_release:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Install dependencies
        run: go mod download
      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
      - name: Generate
        run: go generate ./...
      - name: Install Docker
        if: runner.os == 'Linux'
        run: curl -fsSL https://get.docker.com | bash -s docker
      - name: Install Docker
        if: runner.os == 'macOS'
        run: brew install docker 
      - name: Package for Windows
        if: runner.os == 'Linux'
        run: fyne-cross windows -pull -arch=*
      - name: Package for Linux
        if: runner.os == 'Linux'
        run: fyne-cross linux -pull -arch=*
      - name: Package for MacOS
        # build for macOS not working in linux/windwos, error message:
        # [✗] macOSX SDK path is mandatory
        if: runner.os == 'macOS'
        run: fyne-cross darwin -pull -arch=*
      - name: PreparePackages
        run: |
          mkdir pkg-dist
          for file in fyne-cross/dist/*/* ; do cp "$file" "pkg-dist/$(echo $file | sed -n -E "s/fyne-cross\/dist\/([^\/]+)\/([^\/.]+)([^\/]+)$/\2_${{env.RELEASE_VERSION}}_\1\3/p")" ; done |
          echo "done"
      - name: Uplaod artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "builds_${{runner.os}}"
          path: pkg-dist/*
          if-no-files-found: error

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: builds_*
          merge-multiple: true
          path: pkg-dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          append_body: true
          generate_release_notes: true
          files: |
            pkg-dist/*
            LICENSE
