name: Test

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Install Dependencies
        run: npm ci
      - name: Spellcheck
        run: npm run spellcheck
      - name: Lint
        run: npm run lint
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Testing on ${{ runner.os }}"
        run: echo "running on ${{ runner.os }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install X11 dependencies on MacOS
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz
      - name: Install X11 dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev
      - name: Install dependencies
        # run: go get .
        run: go mod download
      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: Generate
        run: go generate ./...
      - name: Test with Go
        run: go test ./...
      #- name: Build
      #  # run: go build -v ./...
      #  run: fyne package --release
      - name: Setup tmate session for debbuging action
        if: ${{ inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
