name: Test

permissions:
  # statuses needed by actions/commit-status-updater to update commit status
  statuses: write
  # pull-requests needed by actions/commit-status-updater to add comments to PRs
  pull-requests: write 

on: [push, pull_request]

jobs:
  set_pending_status:
    runs-on: ubuntu-latest
    steps:
      - name: "add pending status"
        uses: ouzi-dev/commit-status-updater@v2
        with:
          addHoldComment: "true"
          status: "${{ job.status }}"
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Testing on ${{ runner.os }}"
        run: echo test
      - name: Install X11 dependencies on MacOS
        if: runner.os == 'macOS'
        run: |
          brew --cask install xquartz
      - name: Install X11 dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y xorg-dev
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Install dependencies
        # run: go get .
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Test with Go
        run: go test ./...
      #- name: Test with Go
      #  run: go test -json > TestResults-${{ matrix.go-version }}.json
      #- name: Upload Go test results
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Go-results-${{ matrix.go-version }}
      #    path: TestResults-${{ matrix.go-version }}.json
  set_final_commit_status:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [test]
    steps:
      - name: "set final status ${{ job.status }}"
        uses: ouzi-dev/commit-status-updater@v2
        with:
          addHoldComment: "true"
          status: "${{ job.status }}"
